### ISSUE TITLE
Confirmation Dialog Default Focus

### ISSUE THREAD

**Issue by jsnj** [cartmandos/skin.titan.bingie#15]
Using v1.0.0 on NVidia Shield Android OS

The confirmation dialog's default focus is always on the "NO" button regardless of the setting.

**Comment by cartmandos** [comment]
It caused focus log errors with previous settings, i should remove this option from settings..

**Comment by jsnj** [comment]
Titan is one of the few skins that offer this. Having used Titan for years, it's very noticeable not having it. It's such a simple option but used so often especially for us PVR users who delete shows daily after watching. That extra step is no longer in muscle memory so I often have to start the delete process again having closed the confirmation quickly since it was auto set to NO. Is it simply a matter of a cleaner log file which most users don't see or use or does it cause functional problems? It'd be a shame to lose it. If that log issue can't be resolved, how about just setting default to "NO" and for those of us who find it very useful, we can set it to "YES"

**Comment by cartmandos** [comment]
I'll see what i can do about it. didn't consider it too much when i was trying to resolve bugs/log errors...

**Comment by cartmandos** [comment]
Fixed issue.
https://github.com/cartmandos/skin.titan.bingie/commit/e3cd33fb0efdaeb64bc4e16af1d30b73aee90f2a
