### ISSUE TITLE
Implement a cursor speed control

### ISSUE THREAD

**Issue by kekukui** [cartmandos/skin.titan.bingie#28]
**Create a control which allows the user to change how long the cursor dwells on a line before moving to the next item when a menu navigation key is held down.**

[ On most Kodi skins the cursor moves so fast when a button is held that you cannot easily stop where you want.  For really long menus, `PageUp` & `PageDown` can be used to move the cursor long distances, so the existing (super fast) cursor is really not needed. ]

**Comment by cartmandos** [comment]
Not possible from the skinning engine perspective as far as I know.
