### ISSUE TITLE
DialogExtendedProgressBar.xml

### ISSUE THREAD

**Issue by ko3ni6** [cartmandos/skin.titan.bingie#34]
kodi log: cannot find ... dialogs/extendedprogress/progress/progress/p 0.png
(sorry, no old log by hand)

**Expected behavior**
"dialogs/extendedprogress/progress/p 0.png" found ;)

**OS & Kodi Version (please complete the following information):**
LibreELEC (official): 9.0.1 (Generic.x86_64)
 Linux 4.19.23 #1 SMP x86_64 GNU/Linux
 Titan Bingie 1.0.2

**FIX**
edit skin.titan.bingie/xml/DialogExtendedProgressBar.xml
-- 29:                                        <texture>$INFO[Control.GetLabel(32),dialogs/extendedprogress/**progress**/progress/p,.png]</texture>
++ 29:                                         <texture>$INFO[Control.GetLabel(32),dialogs/extendedprogress/progress/p,.png]</texture>

**Comment by cartmandos** [comment]
Thanks!
