### ISSUE TITLE
Issue :- Widgets (14 Shortcuts to Match Netflix)

### ISSUE THREAD

**Issue by ians325** [cartmandos/skin.titan.bingie#8]
Ive managed to Setup the Netflix Add-on the Menus integrating in you skin but it would be handing to have 14 widgets under on shortcut then i could fulling integrating under one section

**Comment by cartmandos** [comment]
I don't understand what you mean, you can have 14 widgets...You would just have to split them into 2 menu entries. and btw, if you don't want to have the second menu entry you can disable it from the menu but keep the widgets...
