### ISSUE TITLE
Not sure if this Add-on Issue or Skin Issue

### ISSUE THREAD

**Issue by ians325** [cartmandos/skin.titan.bingie#9]
When press info using the amazon vod app on your skin i  get manage and choose art, when select choose art it trys to install art downloader instead of using beef art.  Im running it full bingie mode

**Comment by cartmandos** [comment]
Thanks for pointing it out. I've fixed the issue and will push it soon.

**Comment by cartmandos** [comment]
@ians325 - issue should be fixed in v1. enjoy.
